### ISSUE TITLE
Attributes has already been defined

### ISSUE THREAD

**Issue by viii2050** [2dxgujun/AndroidTagGroup#6]
As i sync the gradle after entering your library it gives me error as, 

'Error:(1) Attribute "textColor" has already been defined'
'Error:(1) Attribute "backgroundColor" has already been defined'

Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\PL\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 1

I checked my color.xml which doesn't have any attribute like 'textColor' or 'backgroundColor'

Help please!

**Comment by 2dxgujun** [comment]
Thanks for your feedback.

The problem is caused by the new attribute names are conflicting with other libraries, and there's no way to tell the system to avoid this situation for now.

It seems i need to make a new release for rename our attribute names  adding some prefix looks like "atg".

See: [Issue22576](https://code.google.com/p/android/issues/detail?id=22576)

**Comment by 2dxgujun** [comment]
Hi, I have promote a new release: v1.4 for fix it, enjoy~

**Comment by viii2050** [comment]
Thanks, working fine!
